---
downloads: ~/.ansible-downloads/

configure_dotfiles: no
configure_terminal: yes
configure_osx: yes

configure_sudoers: no
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

homebrew_installed_packages:
  - ansible
  - conftest
  - ffmpeg
  - gh
  - go
  - git
  - imagemagick
  - k3d
  - openssl@1.1
  - packer
  - pandoc
  - rav1e
  - rclone
  - speedtest-cli
  - ssh-copy-id
  - terraform
  - youtube-dl

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - dropbox
  - powershell

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 409203825, name: "Numbers (6.2)"}
  - { id: 880001334, name: "Reeder (3.2.2)"}
  - { id: 1384080005, name: "Tweetbot (3.3.1)"}
  - { id: 409201541, name: "Pages (8.2)"}
  - { id: 568494494, name: "Pocket (1.8.4)"}
  - { id: 409183694, name: "Keynote (9.2)"}
  - { id: 803453959, name: "Slack (4.1.0)"}
  - { id: 525912054, name: "WiFi Signal (4.1.3)"}
  - { id: 784801555, name: "Microsoft OneNote (16.29)"}
  - { id: 557168941, name: "Tweetbot (2.5.8)"}
mas_email: ""
mas_password: ""

osx_script: "~/.macos --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages:
  []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages:
  []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages:
  []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages:
  []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
